version: "3.8"

services:
  node:
    container_name: bon-appetite-node
    restart: always
    build: ./server
    ports:
      - "8080:8080"
    expose:
      - "6789"
    depends_on: 
      - database
    entrypoint: ['/bin/bash', './entrypoint.sh']

  client:
    container_name: bon-appetite-react
    restart: always
    build: ./client/register
    ports:
      - "80:3000"
    links:
      - "node:client"
    expose:
      - "6789"
  
  database:
    container_name: bon-appetite-database
    image: mysql
    restart: always
    ports:
      - "3305:3306"
    expose:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=database_production      