version: "3.8"

services:
  node:
    container_name: stand-bis-node
    restart: always
    build: ./server
    ports:
      - "8080:8080"

  client:
    container_name: stand-bis-react
    restart: always
    build: ./client/register
    ports:
      - "80:3000"
    links:
      - node